-- 1. Sozlamalar jadvali (Limit, Link, Video)
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Dastlabki qiymatlarni kiritish
INSERT INTO settings (key, value) VALUES 
('referral_limit', '10'),
('closed_group_link', 'https://t.me/+2tnUK6DMs4o0ZDlh'),
('promo_video_id', 'BAACAgIAAxkDAAPVaXC-b3ET4eKq3VscBAUeT_UEZl0AAgqYAAJ3KolLnD9ZI2w87Eo4BA')
ON CONFLICT (key) DO NOTHING;

-- 2. Kanallar jadvali
CREATE TABLE IF NOT EXISTS channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    username TEXT, -- Opsional (tekshirish uchun)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Hozirgi kanallarni kiritish (Misol)
INSERT INTO channels (name, url, username) VALUES
('Matematika Test Quiz', 'https://t.me/matematikatestquiz', 'matematikatestquiz'),
('Freelancer Uzbek', 'https://t.me/freelanser_uzbek', 'freelanser_uzbek'),
('Matematika Test Quiz Guruhi', 'https://t.me/matematikatestquiz_guruh', 'matematikatestquiz_guruh')
ON CONFLICT DO NOTHING;

-- Ruxsatlar (Agar kerak bo'lsa)
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access" ON settings FOR SELECT USING (true);
CREATE POLICY "Public read access" ON channels FOR SELECT USING (true);
-- Yozish faqat service_role ga (bizning botga)
CREATE POLICY "Service write access settings" ON settings FOR ALL USING (true); 
CREATE POLICY "Service write access channels" ON channels FOR ALL USING (true);
