-- G'oliblar jadvali (Winners table)
CREATE TABLE IF NOT EXISTS winners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rank INTEGER NOT NULL UNIQUE, -- 1, 2, 3... o'rinlar
    user_id BIGINT NOT NULL,
    prize TEXT NOT NULL, -- Sovrin nomi (masalan: "100,000 so'm")
    proof_image_id TEXT, -- To'lov isboti rasmi (Telegram file_id)
    announced_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS (Row Level Security)
ALTER TABLE winners ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Public read access winners" ON winners FOR SELECT USING (true);

-- Service write access (bot uchun)
CREATE POLICY "Service write access winners" ON winners FOR ALL USING (true);
